version: '3.7'

services:
  nestjs-app:
    #    image: nestjs-api
    build:
      context: .
      dockerfile: ./nestapps/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager

volumes:
  grafana-storage:

