global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nestjs-app'
    static_configs:
      - targets: ['nestjs-app:3000']
    metrics_path: /metrics
rule_files:
  - "alert.rules.yml"

